### ISSUE TITLE
Exception #0 (ReflectionException): Class Owebia\AdvancedShippingSetting\Model\Carrier does  Magento 2.3 After updating from old advanced shipping to new via composer instructions in Readme

### ISSUE THREAD

**Issue by LiamKarlMitchell** [owebia/magento2-module-advanced-shipping#57]
Receiving this on checkout after updating to Magento 2.3 and updating the advanced shipping module following instructions in the readme to install via Composer.

There is no Owebia directory in app/code either.
Caches cleared.

```
1 exception(s):
Exception #0 (ReflectionException): Class Owebia\AdvancedShippingSetting\Model\Carrier does not exist

Exception #0 (ReflectionException): Class Owebia\AdvancedShippingSetting\Model\Carrier does not exist
#0 /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Owebia\\Advanced...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(49): Magento\Framework\Code\Reader\ClassReader->getConstructor('Owebia\\Advanced...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Owebia\\Advanced...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Owebia\\Advanced...', Array)
#4 /var/www/html/vendor/magento/module-shipping/Model/CarrierFactory.php(74): Magento\Framework\ObjectManager\ObjectManager->create('Owebia\\Advanced...')
#5 /var/www/html/vendor/magento/module-shipping/Model/Config.php(74): Magento\Shipping\Model\CarrierFactory->create('owsh1', '1')
#6 /var/www/html/vendor/magento/module-checkout/Block/Checkout/LayoutProcessor.php(202): Magento\Shipping\Model\Config->getActiveCarriers('1')
#7 /var/www/html/vendor/magento/module-checkout/Block/Checkout/LayoutProcessor.php(174): Magento\Checkout\Block\Checkout\LayoutProcessor->processShippingChildrenComponents(Array)
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Block\Checkout\LayoutProcessor->process(Array)
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->___callParent('process', Array)
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->Magento\Framework\Interception\{closure}(Array)
#11 /var/www/html/generated/code/Magento/Checkout/Block/Checkout/LayoutProcessor/Interceptor.php(26): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->___callPlugins('process', Array, Array)
#12 /var/www/html/vendor/magento/module-checkout/Block/Onepage.php(79): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->process(Array)
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Block\Onepage->getJsLayout()
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Block\Onepage\Interceptor->___callParent('getJsLayout', Array)
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Block\Onepage\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/html/generated/code/Magento/Checkout/Block/Onepage/Interceptor.php(26): Magento\Checkout\Block\Onepage\Interceptor->___callPlugins('getJsLayout', Array, Array)
#17 /var/www/html/vendor/magento/module-checkout/view/frontend/templates/onepage.phtml(21): Magento\Checkout\Block\Onepage\Interceptor->getJsLayout()
#18 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#19 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage\Interceptor), '/var/www/html/v...', Array)
#20 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#21 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Framework\View\Element\Template->_toHtml()
#22 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /var/www/html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('checkout.root')
#24 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('checkout.root')
#25 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('checkout.root', false)
#26 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#27 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('content')
#28 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content', false)
#29 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main', false)
#30 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main')
#31 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main', false)
#32 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('columns', false)
#33 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#34 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('columns', false)
#35 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#36 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#37 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.content', false)
#38 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#39 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#40 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#41 /var/www/html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#42 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('root')
#43 /var/www/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#44 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#45 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#46 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#47 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#48 /var/www/html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#49 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#52 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(39): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#54 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#56 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#57 {main}
```

**Comment by LiamKarlMitchell** [comment]
Solution:

In the app/etc/config.php

Setting active to 0 for owsh1 made the problem go away.

Down further in the same area of the config I saw

'model' => 'Owebia\\AdvancedShippingSetting\\Model\\Carrier',

I changed this as below per https://github.com/owebia/magento2-module-advanced-shipping/blob/master/Model/Carrier.php#L6

'model' => 'Owebia\\AdvancedShipping\\Model\\Carrier',


bin/magento app:config:dump
bin/magento cache:flush
